// Embeds IBM Plex Sans and IBM Plex Mono (latin and greek subsets) in css/fonts.css as
// data: URIs, because browsers refuse to load font files next to a page
// opened from file://. Fetches from Google Fonts; run it again to update:
//
//   node tools/vendor-fonts.mjs
//
// The fonts are under the SIL Open Font License 1.1 (fonts/IBM-Plex-OFL.txt).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const CSS_URL = 'https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700' +
    '&family=IBM+Plex+Mono:wght@400;500&display=swap';
const LICENSE_URL = 'https://raw.githubusercontent.com/IBM/plex/master/LICENSE.txt';
// Google serves woff2 to browsers it recognises.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36';
const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');

async function get(url, type) {
    const res = await fetch(url, { headers: { 'user-agent': UA } });
    if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
    return type === 'text' ? res.text() : Buffer.from(await res.arrayBuffer());
}

// One face per font file: a variable file serves several weights.
const faces = new Map();
for (const block of (await get(CSS_URL, 'text')).split('/* ').slice(1)) {
    if (!block.startsWith('latin */') && !block.startsWith('greek */')) continue;
    const family = /font-family:\s*'([^']+)'/.exec(block)[1];
    const weight = Number(/font-weight:\s*(\d+)/.exec(block)[1]);
    const url = /url\((https:[^)]+)\)/.exec(block)[1];
    const range = /unicode-range:\s*([^;]+);/.exec(block)[1];
    const face = faces.get(url) || { family, url, range, weights: [] };
    face.weights.push(weight);
    faces.set(url, face);
}
let css = '/* IBM Plex Sans and IBM Plex Mono, latin and greek subsets, from Google Fonts, under the SIL Open\n' +
    '   Font License 1.1 (fonts/IBM-Plex-OFL.txt). Generated by tools/vendor-fonts.mjs. */\n';
for (const face of faces.values()) {
    const lo = Math.min(...face.weights), hi = Math.max(...face.weights);
    const data = (await get(face.url)).toString('base64');
    css += `@font-face { font-family: '${face.family}'; font-style: normal; font-weight: ${lo === hi ? lo : `${lo} ${hi}`};` +
        ` font-display: swap; unicode-range: ${face.range};` +
        ` src: url(data:font/woff2;base64,${data}) format('woff2'); }\n`;
}
fs.writeFileSync(path.join(root, 'css', 'fonts.css'), css);
fs.mkdirSync(path.join(root, 'fonts'), { recursive: true });
fs.writeFileSync(path.join(root, 'fonts', 'IBM-Plex-OFL.txt'), await get(LICENSE_URL, 'text'));
console.log(`wrote css/fonts.css (${faces.size} faces, ${(css.length / 1024).toFixed(0)} kB) and fonts/IBM-Plex-OFL.txt`);
